### Script to try out a dummy problem

In [2]:
# Example taken from https://pythonpath.wordpress.com/2012/08/29/cv2-triangulatepoints/

# Includes
import cv2
import numpy as np


# Camera projection matrices
P1 = np.eye(4)
P2 = np.array([[ 0.878, -0.01 ,  0.479, -1.995],
            [ 0.01 ,  1.   ,  0.002, -0.226],
            [-0.479,  0.002,  0.878,  0.615],
            [ 0.   ,  0.   ,  0.   ,  1.   ]])

# Observations of some points matched in two images
a3xN = np.array([[ 0.091,  0.167,  0.231,  0.083,  0.154],
              [ 0.364,  0.333,  0.308,  0.333,  0.308],
              [ 1.   ,  1.   ,  1.   ,  1.   ,  1.   ]])

b3xN = np.array([[ 0.42 ,  0.537,  0.645,  0.431,  0.538],
              [ 0.389,  0.375,  0.362,  0.357,  0.345],
              [ 1.   ,  1.   ,  1.   ,  1.   ,  1.   ]])

# The cv2 method
X = cv2.triangulatePoints( P1[:3], P2[:3], a3xN[:2], b3xN[:2] ) # Why not make -1

# now lindstorm`s implementation should also give us the same thing here

# Remember to divide out the 4th row. Make it homogeneous
X /= X[3]

# Recover the origin arrays from PX
x1 = np.dot(P1[:3],X)
x2 = np.dot(P2[:3],X)

# Again, put in homogeneous form before using them
x1 /= x1[2]
x2 /= x2[2]

print(f"X -- {X}\n\n")
print(f"x1 -- {x1}\n\n")
print(f"x2 -- {x2}\n\n")

X -- [[ 1.00277401  2.00861221  3.01259262  1.00350119  2.01054271]
 [ 4.01217993  4.01031008  4.01743742  4.02958919  4.01894571]
 [11.01977924 12.02856882 13.04163081 12.09159201 13.05497299]
 [ 1.          1.          1.          1.          1.        ]]


x1 -- [[0.09099765 0.1669868  0.23099815 0.08299165 0.15400589]
 [0.36408896 0.33339877 0.30804717 0.33325547 0.30784788]
 [1.         1.         1.         1.         1.        ]]


x2 -- [[0.42002058 0.53709198 0.64501084 0.43105651 0.5379664 ]
 [0.38890031 0.37453153 0.36194222 0.35671333 0.34517832]
 [1.         1.         1.         1.         1.        ]]


